Repository scp756-221/term-project-data-dive, pull requests merged in 2022-04, with the labels that each got.

#42 Functionality added: Remove song from playlist
  s3/v1/app.py
Labels: bug, enhancement

#43 Add song to playlist feature added
  s3/v1/app.py
Labels: enhancement

#45 Added required files
  eks-tpl.mak
  k8s-tpl.mak
Labels: enhancement

#50 Unwanted files deleted in s2
  s2/standalone/.gitignore
  s2/standalone/Dockerfile
  s2/standalone/Makefile
  s2/standalone/README.md
  s2/standalone/app-a1.py
  s2/standalone/app-a2.py
  s2/standalone/app-a3.py
  s2/standalone/builda1.sh
  s2/standalone/builda2.sh
  s2/standalone/builda3.sh
  s2/standalone/ec2-dockerignore
  s2/standalone/gen-random-bytes.sh
  s2/standalone/music.csv
  s2/standalone/odd/music.csv
  s2/standalone/requirements.txt
  s2/standalone/runa1.sh
  s2/standalone/runa2.sh
  s2/standalone/runa3.sh
  s2/standalone/s2-1-file-Dockerfile
  s2/standalone/s2-2-files-Dockerfile
  s2/standalone/self-Dockerfile
  s2/standalone/signon.sh
  s2/standalone/transfer-for-run.sh
  s2/standalone/transfer.sh
  s2/test/Dockerfile
  s2/test/Makefile
  s2/test/music_test.py
  s2/test/requirements.txt
  s2/v1.1/Dockerfile
  s2/v1.1/README.md
  s2/v1.1/a7_app.py
  s2/v1.1/a7_other_dev_app.py
  s2/v1.1/app.py
  s2/v1.1/requirements.txt
  s2/v2/Dockerfile
  s2/v2/app.py
  s2/v2/requirements.txt
Labels: enhancement

#51 Create README.md for s3 service
  s3/README.md
Labels: documentation
